### ISSUE TITLE
Will you update this to 11.1?

### ISSUE THREAD

**Issue by danielhn147** [MrNbaYoh/basehaxx#7]
Please ^_^

**Comment by MrNbaYoh** [comment]
Basehaxx is already compatible with the latest version.

**Comment by danielhn147** [comment]
The site says it's only compatible with 9.0-11.0... Sure it works on 11.1?

**Comment by MrNbaYoh** [comment]
Yeah, I did not update the website ;)

**Comment by danielhn147** [comment]
Is it possible to use basehaxx with only one clean 11.1 3ds?

**Comment by MrNbaYoh** [comment]
No this is not possible at the moment.
