### ISSUE TITLE
Can't launch on 11.1.0-34E

### ISSUE THREAD

**Issue by kernel-panic-enjoyer** [MrNbaYoh/basehaxx#8]
As the title says:
As soon as i try to launch the installer, the O3DS does its flickering thing, but it freezes with a yellow bottom and a black top screen.
I use oot3dhax (powersaves) as an entry point with a 1.4 AS EUR game - clean install.
I've tried several times.

**Comment by MrNbaYoh** [comment]
You can't run the installer right on 11.1, you have to install it on <=11.0

**Comment by kernel-panic-enjoyer** [comment]
Huh, I thought it was available to 11.1, did I miss smth?
Any plans on making it functioning?

**Comment by MrNbaYoh** [comment]
It works on 11.1 but you cannot install it on 11.1, you have to install it on <=11.0 and then launch it on 11.1

**Comment by kernel-panic-enjoyer** [comment]
Oh maan that was somehow not clear for me.
I even just installed the update, because I thought it'll do.
But thanks for the fast answers and the work you put in this 👍
